"""Phase modules — each exports an async run(ctx, http, snapshot) -> list[Finding]."""
from . import (
    tenant,
    federation,
    user_enum,
    m365_services,
    dns_surface,
    auth_surface,
    oauth,
    defense_posture,
    tenant_linkage,
    bing_dorks,
    copilot,
    power_platform,
    azure_resources,
    identity_edges,
    internal_mode,
    # v0.1.6 expanded recon coverage
    ms_public_content,
    azure_subdomain_enum,
    aad_apps,
    github_dorks,
    logic_apps,
    ado_deep,
    onedrive_links,
    intune,
    guest_inference,
    wayback,
    tenant_directory,
    defender_posture,
    package_leaks,
    cert_san,
    # v0.1.7 — SharePoint, Azure data services, MFA gaps, dark corners, authenticated mode
    sharepoint_recon,
    azure_data_services,
    mfa_gaps,
    functions_unauth,
    dark_corners,
    authenticated,
    # v0.1.8 — DNS intel, TKO, headers, full Azure/MS/Entra/SaaS coverage
    dns_intel,
    subdomain_takeover,
    http_headers,
    azure_compute_extras,
    azure_data_extras,
    azure_network_extras,
    microsoft_endpoint,
    dynamics_deep,
    entra_advanced,
    teams_deep,
    office_extras,
    cross_saas,
    breach_intel,
    webhook_hunt,
    subscription_leak,
    power_pages_odata_deep,
    final_gaps,
)

PHASES = {
    "1": ("tenant", tenant),
    "2": ("federation", federation),
    "3": ("user_enum", user_enum),
    "4": ("m365_services", m365_services),
    "5": ("dns_surface", dns_surface),
    "6": ("auth_surface", auth_surface),
    "7": ("oauth", oauth),
    "8": ("defense_posture", defense_posture),
    "9": ("tenant_linkage", tenant_linkage),
    "10": ("bing_dorks", bing_dorks),
    "11": ("copilot", copilot),
    "12": ("power_platform", power_platform),
    "13": ("azure_resources", azure_resources),
    "14": ("identity_edges", identity_edges),
    # v0.1.6 — expanded recon phases
    "15": ("ms_public_content", ms_public_content),
    "16": ("azure_subdomain_enum", azure_subdomain_enum),
    "17": ("aad_apps", aad_apps),
    "18": ("github_dorks", github_dorks),
    "19": ("logic_apps", logic_apps),
    "20": ("ado_deep", ado_deep),
    "21": ("onedrive_links", onedrive_links),
    "22": ("intune", intune),
    "23": ("guest_inference", guest_inference),
    "24": ("wayback", wayback),
    "25": ("tenant_directory", tenant_directory),
    "26": ("defender_posture", defender_posture),
    "27": ("package_leaks", package_leaks),
    "28": ("cert_san", cert_san),
    # v0.1.7 — SharePoint deep, Azure data, MFA gaps, function fuzz, dark corners, auth mode
    "29": ("sharepoint_recon", sharepoint_recon),
    "30": ("azure_data_services", azure_data_services),
    "31": ("mfa_gaps", mfa_gaps),
    "32": ("functions_unauth", functions_unauth),
    "33": ("dark_corners", dark_corners),
    "34": ("authenticated", authenticated),
    # v0.1.8 — full coverage expansion
    "35": ("dns_intel", dns_intel),
    "36": ("subdomain_takeover", subdomain_takeover),
    "37": ("http_headers", http_headers),
    "38": ("azure_compute_extras", azure_compute_extras),
    "39": ("azure_data_extras", azure_data_extras),
    "40": ("azure_network_extras", azure_network_extras),
    "41": ("microsoft_endpoint", microsoft_endpoint),
    "42": ("dynamics_deep", dynamics_deep),
    "43": ("entra_advanced", entra_advanced),
    "44": ("teams_deep", teams_deep),
    "45": ("office_extras", office_extras),
    "46": ("cross_saas", cross_saas),
    "47": ("breach_intel", breach_intel),
    "48": ("webhook_hunt", webhook_hunt),
    "49": ("subscription_leak", subscription_leak),
    "50": ("power_pages_odata_deep", power_pages_odata_deep),
    "51": ("final_gaps", final_gaps),
    "internal": ("internal_mode", internal_mode),
}
